import React from 'react';
export const biometricsDetails = () => <div>biometrics distinct</div>;
export const biometrics_detail_0 = (p:any)=> <div>biometrics 0 HR</div>;
export const biometrics_detail_1 = (p:any)=> <div>biometrics 1 HRV</div>;
export const biometrics_detail_2 = (p:any)=> <div>biometrics 2 sleep</div>;
export const biometrics_detail_3 = (p:any)=> <div>biometrics 3 skin temp</div>;
export const biometrics_detail_4 = (p:any)=> <div>biometrics 4 HR</div>;
export const biometrics_detail_5 = (p:any)=> <div>biometrics 5 HRV</div>;
export const biometrics_detail_6 = (p:any)=> <div>biometrics 6 sleep</div>;
export const biometrics_detail_7 = (p:any)=> <div>biometrics 7 skin temp</div>;
export const biometrics_detail_8 = (p:any)=> <div>biometrics 8 HR</div>;
export const biometrics_detail_9 = (p:any)=> <div>biometrics 9 HRV</div>;
export const biometrics_detail_10 = (p:any)=> <div>biometrics 10 sleep</div>;
export const biometrics_detail_11 = (p:any)=> <div>biometrics 11 skin temp</div>;
export const biometrics_detail_12 = (p:any)=> <div>biometrics 12 HR</div>;
export const biometrics_detail_13 = (p:any)=> <div>biometrics 13 HRV</div>;
export const biometrics_detail_14 = (p:any)=> <div>biometrics 14 sleep</div>;
export const biometrics_detail_15 = (p:any)=> <div>biometrics 15 skin temp</div>;
export const biometrics_detail_16 = (p:any)=> <div>biometrics 16 HR</div>;
export const biometrics_detail_17 = (p:any)=> <div>biometrics 17 HRV</div>;
export const biometrics_detail_18 = (p:any)=> <div>biometrics 18 sleep</div>;
export const biometrics_detail_19 = (p:any)=> <div>biometrics 19 skin temp</div>;